- name: Parallel Deploy for Dev
  hosts: repo_recursioncomic:&env_dev
  vars_files:
    - /home/{{ ANSIBLE_USER }}/ansible/playbook/drupal/vars.yaml
    - vault.yaml

  pre_tasks:
    - name: Check build dir tasks from ansible 
      import_tasks: /home/{{ ANSIBLE_USER }}/ansible/playbook/drupal/tasks/check-build-dir.yaml
  
  tasks:
    - name: Deploy dev tasks from ansible 
      import_tasks: /home/{{ ANSIBLE_USER }}/ansible/playbook/drupal/tasks/2-deploy-dev.yaml