- name: Parallel Deploy for Dev
  hosts: repo_recursioncomic:&env_dev
  vars_files:
    - vars.yaml
    - vault.yaml
  
  pre_tasks:
    - name: Check build dir tasks from ansible 
      import_tasks: /home/{{ ANSIBLE_USER }}/ansible/playbook/tasks/drupal/check-build-dir.yaml
  
  tasks:
    - name: Deploy dev tasks from ansible 
      import_tasks: /home/{{ ANSIBLE_USER }}/ansible/playbook/tasks/drupal/2-deploy-dev.yaml