- name: Runs dev and prod pipelines. Only use in dire circumstances
  hosts: localhost
  vars_files:
  - vars.yaml
- name: Import "Full dev pipeline" playbook
  import_playbook: ./full-dev-pipeline.yaml
- name: Import "Full prod pipeline" playbook
  import_playbook: ./full-prod-pipeline.yaml
