- name: Rebuild dev servers from scratch with full drupal application running
  hosts: localhost
  vars_files:
  - vars.yaml
- name: Import "Wipe dev" playbook
  import_playbook: 0-wipe-dev.yaml
- name: Import "Build composer" playbook
  import_playbook: 1-build-composer.yaml
- name: Import "Deploy dev" playbook
  import_playbook: 2-deploy-dev.yaml
