- name: Promote dev image and deploy to all prod servers
  hosts: localhost
  vars_files:
  - vars.yaml
- name: Import "Bake image" playbook
  import_playbook: 3-bake-image.yaml
- name: Import "Deploy prod" playbook
  import_playbook: 4-deploy-prod.yaml
