ANSIBLE_USER: kevin
git_dir: /home/{{ ANSIBLE_USER }}/{{ APPLICATION }}
APPLICATION: recursioncomic
netbox_dns: netbox.thejfk.ca
certs_dir: "/opt/certs"
keepalived_conf: "keepalived.conf"
keepalived_dir: "/etc/keepalived/"
INTERFACE: eth0   
internal_router: 191
dev_db: 192.168.80.50
dev1: 192.168.80.15
dev2: 192.168.80.16
internal_vip: 192.168.80.17
prod1: 192.168.80.18
prod2: 192.168.80.19
external_vip: 192.168.80.20
prod_db: 192.168.80.61
external_router: 201
nfs_target_dir: /var/www/web/sites/default/files
nfs_server: 192.168.11.20
nfs_share: /mnt/yes/gitbuilds/{{ APPLICATION }}/files
dbName: "{{ APPLICATION }}"
username: "{{ APPLICATION }}"
db_password: P7jnXnxNB468bVdxGQUm
drush: /var/www/vendor/drush/drush/drush