$ANSIBLE_VAULT;1.1;AES256
33333832396361373631623032373038326530633630653366383162653135393234373437353032
3563373231373332613836383234643132306535383637300a303631363464663436373137656261
37323334336164616138373437386632386464316438313031363966653930373333363330343563
3962653830633830640a616563303664316531636233396561623234313161363637303462343137
38616635343663633037383739363966373332346436613966336561323962373534653263366664
31333566653131373137313463333536333634333061643335636262386134613836343236383137
65633733613263316466396265393561373932316238336666376532626430626633393439663861
38343861383434333763356163313233653633363163663632343338303139343231303263353235
31373062646361623932636230313532623032346365383362323734643537303831643537636332
38623562353365306361346234356636646438346339363031623064643636656234333938333237
39363065386537386235623435656338656337333439343130363138343766363064306139373438
66393331626132636261313661383137336264633237343935313661323864386363613064336261
36326232313234623332616665353337633266306162663230313532346633313836613161613030
61333863623231646637306230366562306432386434633063333234383639653835343933653438
62656365666264663632353838333036653232373763363738633136653133313661326635356635
64353734353530356639
