$ANSIBLE_VAULT;1.1;AES256
36363937336631333336343533613034386337663239636561366365613766646234623465653663
3862316433346534323631613434613261633365336638380a316662363130373134346262363062
31613162393366323565326436633937616134333834353032636430363534633736393630393038
6639376535383530370a636531623234653561376636666235656166353135643965626531653234
63623238386261643733313663323836626236616561633030343264336566383734363139373662
63356235373165616236336639363230346135393965306339383831633639373030663765356235
626233613739616334386431326462313633
